title: "Mantov's Portfolio"
description: "Mantov's Portfolio | Projects, Research & Articles"
author: Manuel Tovar

url: "https://MantovBiz.github.io"
baseurl: ""

theme: minima

header_pages:
  - index.md
  - about.md
  - projects.md
  - articles.md

plugins:
  - jekyll-feed
