title: "Mantov's Portfolio"
description: "Projects, Research & Articles"
author: Manuel Tovar
url: "https://MantovBiz.github.io"
baseurl: ""

# Theme
theme: minima

# Navigation
header_pages:
  - index.md
  - about.md
  - projects.md
  - articles.md

# Plugins
plugins:
  - jekyll-feed

# Build settings
markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM
  syntax_highlighter: rouge
